Fix pkg-config on Windows

diff --git a/.github/actions/build-and-test/action.yml b/.github/actions/build-and-test/action.yml
--- a/.github/actions/build-and-test/action.yml
+++ b/.github/actions/build-and-test/action.yml
@@ -53,10 +53,18 @@ runs:
       shell: bash
       run: |
         ${{ inputs.executable }} build --workspace --target ${{ inputs.target }} --release ${{ steps.set-feature-flags.outputs.cargo-features }} $CARGO_VERBOSE
-    - name: "cargo test"
+    - name: "cargo test (non-Windows)"
+      if: ${{ runner.os != 'Windows' }}
       shell: bash
       run: |
-        ${{ inputs.executable }} test --workspace --target ${{ inputs.target }} ${{ inputs.test-flags }} --release ${{ steps.set-feature-flags.outputs.cargo-features }} $CARGO_VERBOSE
+        ${{ inputs.executable }} test --workspace --target ${{ inputs.target }} ${{ inputs.test-flags }} --release ${{ steps.set-feature-flags.outputs.cargo-features }} $CARGO_VERBOSE -- --nocapture
+    # TODO: Using powershell because, for some reason, MinGW bash fails to locate some DLL we're using, and I can't figure out why
+    #       Best guess is `api-ms-win-core-synch-l1-2-0.dll`, but that's an API Set and should just automatically exist!
+    - name: "carg test (Windows)"
+      if: ${{ runner.os == 'Windows' }}
+      shell: pwsh
+      run: |
+        ${{ inputs.executable }} test --workspace --target ${{ inputs.target }} ${{ inputs.test-flags }} --release ${{ steps.set-feature-flags.outputs.cargo-features }} $CARGO_VERBOSE -- --nocapture
     - name: "Package test failure files"
       id: package-tests
       if: ${{ failure() }}
@@ -64,13 +72,14 @@ runs:
       run: |
         artifact_dir="test_failures"
         mkdir -p "$artifact_dir"
+        mv "target/${{ inputs.target }}/release/deps"/*.exe "$artifact_dir" || true
         mv *.observed "$artifact_dir" || true
         mv *.expected "$artifact_dir" || true
         if [ -n "$(ls -A $artifact_dir)" ]; then
-          echo "failure-artifacts=true" >> "$GITHUB_OUTPUTS"
+          echo "failure-artifacts=true" >> "$GITHUB_OUTPUT"
         fi
     - name: "Publish packaged test failures"
-      if: ${{ steps.package-tests.outputs.failure-artifacts }}
+      if: ${{ failure() && steps.package-tests.outputs.failure-artifacts == 'true' }}
       uses: actions/upload-artifact@v4
       with:
         name: test-failures-${{ inputs.target }}
